version: '3.8'
services:
  postgres_db:
    container_name: postgres_db_flyway
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_flyway
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_flyway:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  volume_postgres_db_flyway:
    external: false